spring.application.name=clientService
server.port=${CLIENT_SERVICE_PORT}
# Security
jwt.secret=${JWT_SECRET}
banka.security.issuer=banka1
banka.security.id=id
banka.security.roles-claim=roles
#ms
banka.security.expiration-time=3600000
banka.security.permissions-claim=permissions
banka.security.permit-all=/v3/api-docs/**,/v3/api-docs.yaml,/swagger-ui/**,/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.server-url=${CLIENT_SERVICE_URL}
management.endpoints.web.exposure.include=health,info
# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
rabbitmq.queue=${NOTIFICATION_QUEUE}
rabbitmq.exchange=${NOTIFICATION_EXCHANGE}
rabbitmq.routing-key=${NOTIFICATION_ROUTING_KEY}
# Database
spring.datasource.url=jdbc:postgresql://${CLIENT_SERVICE_DB_HOST}:${CLIENT_SERVICE_DB_PORT}/${CLIENT_SERVICE_DB_NAME}
spring.datasource.username=${CLIENT_SERVICE_DB_USER}
spring.datasource.password=${CLIENT_SERVICE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# Liquibase handles DDL, Hibernate only validates
spring.jpa.hibernate.ddl-auto=validate
# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
# Rate limiting
rate-limit.max-requests=10
rate-limit.window-ms=60000

company.observability.starter.user-id-mdc-enabled=true
